### PR TITLE
BSHIFT-12: Adds support for VDEF statements

### PR DESCRIPTION
**Pull request by fooker**
VDEFs are now parsed and calculated inside backshift. The obsolete
syntax for (G)PRINT statements is still supported but implementation has
changed to use an interim VDEF.

This requires an update to flot-legend, as the calculated values must be
passed to the legend for rendering.

### CODE REVIEW

**Comment by fooker** [comment]
This requires https://github.com/j-white/flot-legend/pull/3 to be released beforehand.

**Comment by j-white** [comment]
I've migrated the flot-legend project into the OpenNMS organization.

We can release flot-legend 2.0.0 once the unit tests are fixed: https://travis-ci.org/OpenNMS/flot-legend/jobs/176732366

**Comment by j-white** [comment]
flot-legend 2.0.0 has been tagged, please update the bower.json file to reference the 2.0.0 tag of flot-legend in the OpenNMS organization.

**Comment by fooker** [comment]
CI succeeded. Looks like it's ready to merge.

**Pull request merged**
